application: pixeljs
version: 1
runtime: python
api_version: 1

handlers:
- url: /public
  static_dir: public
- url: /public/css/
  static_dir: public/css
- url: /public/js
  static_dir: public/js
- url: /public/js/ui
  static_dir: public/js/ui
- url: /public/images
  static_dir: public/images
- url: /public/farbtastic
  static_dir: public/farbtastic
- url: /.*
  script: main.py
